apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: soccersite
  name: soccersite
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: soccersite
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: soccersite
    spec:
      containers:
      - image: denzelawuah/soccersite:v2
        imagePullPolicy: IfNotPresent
        name: soccersite-service
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: soccersite
  name: soccersite
  namespace: default
spec:
  ports:
  - port: 4200
    protocol: TCP
    targetPort: 80
  selector:
    app: soccersite
  sessionAffinity: None
  type: LoadBalancer