# Use user/password credentials
version: '3.1'

services:

  postgresdb:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: denzel
      POSTGRES_PASSWORD: 123pass
      POSTGRES_DB: soccersitedb
